### PR TITLE
Add revert reason

### PR DESCRIPTION
**Pull request by janayama**
The idea of this PR is adding the `revertReason` into the failed transaction payload. 

This affects to the failing transaction. It will ask to the node for the failing transaction.

In the new version of web3j that was integrated into Eventeum it was added the revert reason in the EthCall: https://github.com/web3j/web3j/blob/23beb6f394afabe143f1904d8179180152f8f212/core/src/main/java/org/web3j/protocol/core/methods/response/EthCall.java#L44

The ethCall is a query call that simulates the function call but without performing any change in the chain. It only adds a bit delay in emitting the failing event because it is calling the node to check the revert reason.

We think this is a very big feature to have in Eventeum because it notifies about the error inside the transaction failed event payload.

### CODE REVIEW

**Comment by craigwilliams84** [comment]
Hey thanks for this, its a cool feature!  Because of the added overhead, could we make obtaining and setting the revert reason an optional feature, based on some configuration?  Also, do all clients support this?

**Comment by janayama** [comment]
> could we make obtaining and setting the revert reason an optional feature, based on some configuration?

Sure, we can add that configurable. Sounds good `addRevertReason: true/false` for you?

> Also, do all clients support this?

Parity and Ganache are not working with it, in parity they have an issue open: https://github.com/paritytech/parity-ethereum/issues/8068

How the code is done, if the client does not support it is not failing, it only returns null.

From the solidity code:

Source: https://github.com/ethereum/solidity/pull/3364/files#diff-093c7b9d55386ce8842208ea6e7e9ee2R542-R551

> The provided string is :ref:`abi-encoded <ABI>` as if it were a call to a function Error(string). In the above example, revert("Not enough Ether provided."); returns the following hexadecimal as error return data:

```
0x08c379a0                                                         // Function selector for Error(string)
0x0000000000000000000000000000000000000000000000000000000000000020 // Data offset
0x000000000000000000000000000000000000000000000000000000000000001a // String length
0x4e6f7420656e6f7567682045746865722070726f76696465642e000000000000 // String data
```

So in the call it always return something starting with `0x08c379a0`.

And here is how web3j got the revert reason from the return of the `ethCall`: https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/methods/response/EthCall.java#L29

So it is just returning null when getting the error in ganache or parity. For the rest is working fine, which are probably most of them.

---

My suggestion will be adding the config param and explaining in the readme that for now it will not be supported for parity and ganache

**Comment by craigwilliams84** [comment]
Ok cool, sounds good!

> The one you prefer?
Probably the former as I would rather not change the configuration format.  An `addTransactionRevertReason` property could also potentially be added at the node level, with the transaction level config taking precedence.

**Comment by janayama** [comment]
> addTransactionRevertReason property could also potentially be added at the node level

Yeah let's do like that.

**Comment by janayama** [comment]
@craigwilliams84 changed!

**Comment by craigwilliams84** [comment]
Great, thanks.  Sorry to be picky, but can I make one last request...

Rather than injecting the `Environment` and constructing a `NodeSettings` in `DefaultTransactionMonitoringBlockListener`, could you add the `@Component` annotation to `NodeSettings`, and inject it into the listener instead?  It has to be constructed in `BlockchainServiceRegistrar` unfortunately, because it's too early in the bean lifecycle.

**Comment by janayama** [comment]
no picky at all, sounds good. Are you okay if I create a public function in `NodeSettings` called `getNode(String nodeName)`. 

So it is easy to do: `nodeSettings.getNode('myNodeName')`. 

That function will iterate the nodes list to get the correct one. Or we map the Nodes and we use the nodeName as index in stead of what we have now: `List<Node> nodes;`

But I think iterating should not be a very big deal... As you prefer.

**Comment by craigwilliams84** [comment]
Yep, thats a good idea.  I also like changing to a map for the slight performance increase.

**Comment by janayama** [comment]
@craigwilliams84 Done. I moved from list to a mapping by name 👍

**Pull request merged**
